use_frameworks!

platform :ios, '10.0'

target 'KQTaskNetworkManager_Example' do
  pod 'KQTaskNetworkManager', :path => '../'

  target 'KQTaskNetworkManager_Tests' do
    inherit! :search_paths

    
  end
end
